/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacientes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguelangelo
 */
public class HistoriaPaciente extends javax.swing.JInternalFrame {

    Connection conecta;
    JTextField txtIdPaciente_C;
    
    /**
     * Creates new form HistoriaPaciente
     */
    public HistoriaPaciente() {
        initComponents();
         IniciaBD();
        llenaTablaPacientes();
    }
    
    public HistoriaPaciente(JTextField txtIdProducto) {
        initComponents();
         IniciaBD();
        llenaTablaPacientes();
        this.txtIdPaciente_C=txtIdPaciente_C;
    }
    
      public void IniciaBD(){
            try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conecta = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/base_consultorio","root","");
            
            }catch (Exception ex){
            ex.printStackTrace();
            }
       }

      public void llenaTablaPacientes() {
    try{
        DefaultTableModel model = new DefaultTableModel();
        TablaHistorial.setModel(model);
        PreparedStatement consulta = conecta.prepareStatement(""
                + "SELECT * FROM pacientes");
        ResultSet rs = consulta.executeQuery();
        ResultSetMetaData rsMd = rs.getMetaData();
        int numeroColumnas = rsMd.getColumnCount();
        for (int i=1; i<= numeroColumnas; i++){
            model.addColumn(rsMd.getColumnLabel(i));
        }
    while (rs.next()){
        Object[] fila = new Object[numeroColumnas];
        for (int j =1; j<= numeroColumnas; j++){
            fila[j-1]= rs.getObject(j);
        }
        model.addRow(fila);
    }
    
    
}catch(Exception e){
        e.printStackTrace();
    }
}
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHistorial = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtBusquedaNP = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        txtBusquedaAP = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        txtBusquedaDP = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        txtBusquedaTP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaHistorial);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Historial De Pacientes");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtBusquedaNP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaNPKeyReleased(evt);
            }
        });
        txtBusquedaNP.setBounds(0, 0, 329, 30);
        jLayeredPane1.add(txtBusquedaNP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Nombre", jLayeredPane1);

        txtBusquedaAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaAPKeyReleased(evt);
            }
        });
        txtBusquedaAP.setBounds(0, 0, 329, 30);
        jLayeredPane2.add(txtBusquedaAP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Apellido", jLayeredPane2);

        txtBusquedaDP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaDPKeyReleased(evt);
            }
        });
        txtBusquedaDP.setBounds(0, 0, 329, 30);
        jLayeredPane3.add(txtBusquedaDP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Direccion", jLayeredPane3);

        txtBusquedaTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaTPKeyReleased(evt);
            }
        });
        txtBusquedaTP.setBounds(0, 0, 329, 30);
        jLayeredPane4.add(txtBusquedaTP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Telefono", jLayeredPane4);

        jLabel3.setText("Buscar Por:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnSalir))
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .add(284, 284, 284))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtBusquedaNPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaNPKeyReleased
        // TODO add your handling code here:
        try{
            DefaultTableModel model = new DefaultTableModel();
            TablaHistorial.setModel(model);

            PreparedStatement consulta = conecta.prepareStatement(""
                + "SELECT * FROM pacientes WHERE nombre LIKE ?");
            consulta.setString( 1, "%"+txtBusquedaNP.getText()+"%");

            /*
            PreparedStatement consulta = conecta.prepareStatement(""
                + "SELECT * FROM pacientes WHERE nombre "
                + "MATCH(nombre,apellido_paterno,apellido_materno) AGAINST (?)");
            consulta.setString( 1, txtBusquedaCP.getText());
            */
            ResultSet rs = consulta.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int numeroColumnas = rsMd.getColumnCount();
            for(int i = 1; i <= numeroColumnas; i++){
                model.addColumn(rsMd.getColumnLabel(i));
            }

            while(rs.next()){
                Object[] fila = new Object[numeroColumnas];
                for(int j=1; j <= numeroColumnas; j++){
                    fila[j-1] = rs.getObject(j);
                }

                model.addRow(fila);
            }

        }catch(Exception e){
            e.printStackTrace();

        }
    }//GEN-LAST:event_txtBusquedaNPKeyReleased

    private void txtBusquedaAPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaAPKeyReleased
        // TODO add your handling code here:
        try{
            DefaultTableModel model = new DefaultTableModel();
            TablaHistorial.setModel(model);

            PreparedStatement consulta = conecta.prepareStatement(""
                + "SELECT * FROM pacientes WHERE apellido_paterno LIKE ?");
            consulta.setString( 1, "%"+txtBusquedaAP.getText()+"%");

            /*
            PreparedStatement consulta = conecta.prepareStatement(""
                + "SELECT * FROM pacientes WHERE nombre "
                + "MATCH(nombre,apellido_paterno,apellido_materno) AGAINST (?)");
            consulta.setString( 1, txtBusquedaCP.getText());
            */
            ResultSet rs = consulta.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int numeroColumnas = rsMd.getColumnCount();
            for(int i = 1; i <= numeroColumnas; i++){
                model.addColumn(rsMd.getColumnLabel(i));
            }

            while(rs.next()){
                Object[] fila = new Object[numeroColumnas];
                for(int j=1; j <= numeroColumnas; j++){
                    fila[j-1] = rs.getObject(j);
                }

                model.addRow(fila);
            }

        }catch(Exception e){
            e.printStackTrace();

        }
    }//GEN-LAST:event_txtBusquedaAPKeyReleased

    private void txtBusquedaDPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaDPKeyReleased
        // TODO add your handling code here:
        try{
            DefaultTableModel model = new DefaultTableModel();
            TablaHistorial.setModel(model);

            PreparedStatement consulta = conecta.prepareStatement(""
                + "SELECT * FROM pacientes WHERE direccion LIKE ?");
            consulta.setString( 1, "%"+txtBusquedaDP.getText()+"%");

            /*
            PreparedStatement consulta = conecta.prepareStatement(""
                + "SELECT * FROM pacientes WHERE nombre "
                + "MATCH(nombre,apellido_paterno,apellido_materno) AGAINST (?)");
            consulta.setString( 1, txtBusquedaCP.getText());
            */
            ResultSet rs = consulta.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int numeroColumnas = rsMd.getColumnCount();
            for(int i = 1; i <= numeroColumnas; i++){
                model.addColumn(rsMd.getColumnLabel(i));
            }

            while(rs.next()){
                Object[] fila = new Object[numeroColumnas];
                for(int j=1; j <= numeroColumnas; j++){
                    fila[j-1] = rs.getObject(j);
                }

                model.addRow(fila);
            }

        }catch(Exception e){
            e.printStackTrace();

        }
    }//GEN-LAST:event_txtBusquedaDPKeyReleased

    private void txtBusquedaTPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaTPKeyReleased
        // TODO add your handling code here:
        try{
            DefaultTableModel model = new DefaultTableModel();
            TablaHistorial.setModel(model);

            PreparedStatement consulta = conecta.prepareStatement(""
                + "SELECT * FROM pacientes WHERE telefono LIKE ?");
            consulta.setString( 1, "%"+txtBusquedaTP.getText()+"%");

            /*
            PreparedStatement consulta = conecta.prepareStatement(""
                + "SELECT * FROM pacientes WHERE nombre "
                + "MATCH(nombre,apellido_paterno,apellido_materno) AGAINST (?)");
            consulta.setString( 1, txtBusquedaCP.getText());
            */
            ResultSet rs = consulta.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int numeroColumnas = rsMd.getColumnCount();
            for(int i = 1; i <= numeroColumnas; i++){
                model.addColumn(rsMd.getColumnLabel(i));
            }

            while(rs.next()){
                Object[] fila = new Object[numeroColumnas];
                for(int j=1; j <= numeroColumnas; j++){
                    fila[j-1] = rs.getObject(j);
                }

                model.addRow(fila);
            }

        }catch(Exception e){
            e.printStackTrace();

        }
    }//GEN-LAST:event_txtBusquedaTPKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoriaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoriaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoriaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoriaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoriaPaciente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaHistorial;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtBusquedaAP;
    private javax.swing.JTextField txtBusquedaDP;
    private javax.swing.JTextField txtBusquedaNP;
    private javax.swing.JTextField txtBusquedaTP;
    // End of variables declaration//GEN-END:variables
}
