/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuarios;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguelangelo
 */
public class frmUsuarios extends javax.swing.JInternalFrame {

    Connection conecta;
    
    /**
     * Creates new form frmUsuarios
     */
    public frmUsuarios() {
        initComponents();
        IniciaBD();
        llenaTablaUsuarios();
        txtID_U.setVisible(false);
    }

    public void IniciaBD(){
            try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conecta = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/base_consultorio","root","");
            
            }catch (Exception ex){
            ex.printStackTrace();
            }
       }
    
    public void llenaTablaUsuarios() {
    try{
        DefaultTableModel model = new DefaultTableModel();
        TablaUsuarios.setModel(model);
        PreparedStatement consulta = conecta.prepareStatement(""
                + "SELECT * FROM usuarios");
        ResultSet rs = consulta.executeQuery();
        ResultSetMetaData rsMd = rs.getMetaData();
        int numeroColumnas = rsMd.getColumnCount();
        for (int i=1; i<= numeroColumnas; i++){
            model.addColumn(rsMd.getColumnLabel(i));
        }
    while (rs.next()){
        Object[] fila = new Object[numeroColumnas];
        for (int j =1; j<= numeroColumnas; j++){
            fila[j-1]= rs.getObject(j);
        }
        model.addRow(fila);
    }
    
    
}catch(Exception e){
        e.printStackTrace();
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombreU_U = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtApellidoP_U = new javax.swing.JTextField();
        txtApellidoM_U = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombre_U = new javax.swing.JTextField();
        txtEspecialidad_U = new javax.swing.JTextField();
        txtID_U = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtBusquedaCU = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        txtBusquedaCU2 = new javax.swing.JTextField();
        txtContrasena_U = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Buscar Por:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsuarios);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Consulta de Usuarios");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre(s):");

        jLabel4.setText("Especialidad:");

        jLabel5.setText("Nombre de Usuario:");

        jLabel6.setText("Apellido Paterno:");

        jLabel7.setText("Apellido Materno:");

        jLabel8.setText("ContraseÃ±a:");

        txtBusquedaCU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaCUKeyReleased(evt);
            }
        });
        txtBusquedaCU.setBounds(0, 0, 329, 30);
        jLayeredPane1.add(txtBusquedaCU, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Nombre", jLayeredPane1);

        txtBusquedaCU2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaCU2KeyReleased(evt);
            }
        });
        txtBusquedaCU2.setBounds(0, 0, 329, 30);
        jLayeredPane2.add(txtBusquedaCU2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Usuario", jLayeredPane2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel1))
                                .add(26, 26, 26)
                                .add(jLabel2)
                                .add(0, 290, Short.MAX_VALUE)))
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel7)
                            .add(jLabel3)
                            .add(jLabel6))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtApellidoP_U)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtApellidoM_U)
                            .add(txtNombre_U, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 191, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel5)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                .add(layout.createSequentialGroup()
                                    .add(txtID_U, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(8, 8, 8)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jLabel8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtEspecialidad_U, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtNombreU_U)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txtContrasena_U, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnModificar)
                            .add(btnEliminar)
                            .add(btnSalir))
                        .add(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 32, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(txtEspecialidad_U, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btnModificar))
                        .add(11, 11, 11)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtNombreU_U, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5)
                            .add(btnEliminar))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8)
                            .add(btnSalir)
                            .add(txtContrasena_U, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtNombre_U, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtApellidoP_U, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtApellidoM_U, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel7))))
                .add(11, 11, 11)
                .add(txtID_U, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String ID_U = txtID_U.getText();

        try{
            PreparedStatement elimina_cita = conecta.prepareStatement(""
                + "DELETE FROM usuarios WHERE ID_usuario=?");

            elimina_cita.setString(1, ID_U);

            elimina_cita.executeUpdate();

            VaciaCampos();
            llenaTablaUsuarios();

        }catch(Exception e){
            e.printStackTrace();
        }
        {
            JOptionPane.showMessageDialog(null, "La informacion del paciente fue eliminada con exito.");
            return;
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String ID_U = txtID_U.getText();
        String Nombre_U = txtNombre_U.getText();
        String ApellidoP_U = txtApellidoP_U.getText();
        String ApellidoM_U = txtApellidoM_U.getText();
        String Especialidad_U = txtEspecialidad_U.getText();
        String NombreU_U = txtNombreU_U.getText();
        String Contrasena_U = txtContrasena_U.getText();

        if (Nombre_U.length() == 0 || ApellidoP_U.length() == 0 ||
            ApellidoM_U.length() == 0 || Especialidad_U.length() == 0 ||
            NombreU_U.length() == 0 || Contrasena_U.length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Es neceario llenar todos los campos para realizar la modificacion de usuario.");
            return;
        }

        try{
            PreparedStatement modifica_usuario = conecta.prepareStatement(""
                + "UPDATE usuarios SET "
                + "nombre=?, apellido_paterno=?,apellido_materno=?,especialidad=?"
                + ",usuario=?,contrasena=? WHERE ID_usuario=?");
            modifica_usuario.setString(1, Nombre_U);
            modifica_usuario.setString(2, ApellidoP_U);
            modifica_usuario.setString(3, ApellidoM_U);
            modifica_usuario.setString(4, Especialidad_U);
            modifica_usuario.setString(5, NombreU_U);
            modifica_usuario.setString(6, Contrasena_U);
            modifica_usuario.setString(7, ID_U);

            modifica_usuario.executeUpdate();

            VaciaCampos();
            llenaTablaUsuarios();

        }catch(Exception e){
            e.printStackTrace();
        }
        {
            JOptionPane.showMessageDialog(null, "La informacion del paciente fue modificada con exito.");
            return;
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void TablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosMouseClicked
        // TODO add your handling code here:
        String Nombre_U = (String) TablaUsuarios.getValueAt( TablaUsuarios.getSelectedRow(), 1);
        String ApellidoP_U = (String) TablaUsuarios.getValueAt( TablaUsuarios.getSelectedRow(), 2);
        String ApellidoM_U = (String) TablaUsuarios.getValueAt( TablaUsuarios.getSelectedRow(), 3);
        String Especialidad_U = (String) TablaUsuarios.getValueAt( TablaUsuarios.getSelectedRow(), 4);
        String NombreU_U = (String) TablaUsuarios.getValueAt( TablaUsuarios.getSelectedRow(), 5);
        String Contrasena_U = (String) TablaUsuarios.getValueAt( TablaUsuarios.getSelectedRow(), 5);
        int ID_U=(Integer) TablaUsuarios.getValueAt( TablaUsuarios.getSelectedRow(), 0);

        txtID_U.setText(Integer.toString(ID_U));
        txtNombre_U.setText(Nombre_U);
        txtApellidoP_U.setText(ApellidoP_U);
        txtApellidoM_U.setText(ApellidoM_U);
        txtEspecialidad_U.setText(Especialidad_U);
        txtNombreU_U.setText(NombreU_U);
        txtContrasena_U.setText(Contrasena_U);
    }//GEN-LAST:event_TablaUsuariosMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void txtBusquedaCUKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaCUKeyReleased
        // TODO add your handling code here:
                       try{            
            DefaultTableModel model = new DefaultTableModel();
           TablaUsuarios.setModel(model);
               
            PreparedStatement consulta = conecta.prepareStatement(""
                    + "SELECT * FROM usuarios WHERE nombre LIKE ?");                            
            consulta.setString( 1, "%"+txtBusquedaCU.getText()+"%");
           
            /*
            PreparedStatement consulta = conecta.prepareStatement(""
                    + "SELECT * FROM pacientes WHERE nombre "
                    + "MATCH(nombre,apellido_paterno,apellido_materno) AGAINST (?)");                              
            consulta.setString( 1, txtBusquedaCP.getText());
           */
            ResultSet rs = consulta.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int numeroColumnas = rsMd.getColumnCount();            
            for(int i = 1; i <= numeroColumnas; i++){
                model.addColumn(rsMd.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object[] fila = new Object[numeroColumnas];
                for(int j=1; j <= numeroColumnas; j++){
                    fila[j-1] = rs.getObject(j);
                }                
                
                model.addRow(fila);
            }

        }catch(Exception e){
            e.printStackTrace();
                    
        }
    }//GEN-LAST:event_txtBusquedaCUKeyReleased

    private void txtBusquedaCU2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaCU2KeyReleased
        // TODO add your handling code here:
                         try{            
            DefaultTableModel model = new DefaultTableModel();
           TablaUsuarios.setModel(model);
               
            PreparedStatement consulta = conecta.prepareStatement(""
                    + "SELECT * FROM usuarios WHERE usuario LIKE ?");                            
            consulta.setString( 1, "%"+txtBusquedaCU2.getText()+"%");
           
            /*
            PreparedStatement consulta = conecta.prepareStatement(""
                    + "SELECT * FROM pacientes WHERE nombre "
                    + "MATCH(nombre,apellido_paterno,apellido_materno) AGAINST (?)");                              
            consulta.setString( 1, txtBusquedaCP.getText());
           */
            ResultSet rs = consulta.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int numeroColumnas = rsMd.getColumnCount();            
            for(int i = 1; i <= numeroColumnas; i++){
                model.addColumn(rsMd.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object[] fila = new Object[numeroColumnas];
                for(int j=1; j <= numeroColumnas; j++){
                    fila[j-1] = rs.getObject(j);
                }                
                
                model.addRow(fila);
            }

        }catch(Exception e){
            e.printStackTrace();
                    
        }
    }//GEN-LAST:event_txtBusquedaCU2KeyReleased

    public void VaciaCampos(){
        txtNombre_U.setText("");
        txtApellidoP_U.setText("");
        txtApellidoM_U.setText("");
        txtEspecialidad_U.setText("");
        txtNombreU_U.setText("");
        txtContrasena_U.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApellidoM_U;
    private javax.swing.JTextField txtApellidoP_U;
    private javax.swing.JTextField txtBusquedaCU;
    private javax.swing.JTextField txtBusquedaCU2;
    private javax.swing.JPasswordField txtContrasena_U;
    private javax.swing.JTextField txtEspecialidad_U;
    private javax.swing.JTextField txtID_U;
    private javax.swing.JTextField txtNombreU_U;
    private javax.swing.JTextField txtNombre_U;
    // End of variables declaration//GEN-END:variables
}
